_target_: datasets.embeds.MRIEmbedsDataset
modality: mri
data_root: data/mri
encoder: CLIP
pool_anomalies: false
seed: 42

datasets:
  Brain Tumor MRI Dataset:
    tag: train
    cap: 2000
  BraTS2021:
    tag: train
    cap: 2000
  Br35H:
    tag: train
    cap: 2000
  BrainTumor:
    tag: test
    cap: null
  brain_tumor_dataset:
    tag: test
    cap: null
  brisc2025:
    tag: test
    cap: 2000
  Epic and CSCR hospital Dataset:
    tag: test
    cap: 2000
  Alzheimer_s Dataset:
    tag: test
    cap: 2000
  OASIS Alzheimer's Detection:
    tag: test
    cap: 2000
