_target_: datasets.embeds.OCTEmbedsDataset
modality: oct
data_root: data/oct
encoder: CLIP
cap: true
max_dataset_size: 10000
seed: 42

datasets:
  OCT2017:
    tag: train
    labels: null
  Retinal OCT images:
    tag: train
    labels: null
  ZhangLabData OCT:
    tag: train
    labels: null
  ARMD OCT:
    tag: test
    labels: null
  RetinalOCT_Dataset:
    tag: test
    labels: null
